s = '''
IncomeSource1_GMI = models.CharField(default='0',max_length=500)
IncomeSource1_Job = models.CharField(default='',max_length=500)
IncomeSource1_Employer = models.CharField(default='',max_length=500)
IncomeSource2_GMI = models.CharField(default='0',max_length=500)
IncomeSource2_Job = models.CharField(default='',max_length=500)
IncomeSource2_Employer = models.CharField(default='',max_length=500)
IncomeSource3_GMI = models.CharField(default='0',max_length=500)
IncomeSource3_Job = models.CharField(default='',max_length=500)
IncomeSource3_Employer = models.CharField(default='',max_length=500)
IncomeSource4_GMI = models.CharField(default='0',max_length=500)
IncomeSource4_Job = models.CharField(default='',max_length=500)
IncomeSource4_Employer = models.CharField(default='',max_length=500)
IncomeSource5_GMI = models.CharField(default='0',max_length=500)
IncomeSource5_Job = models.CharField(default='',max_length=500)
IncomeSource5_Employer = models.CharField(default='',max_length=500)
fico_model_used = models.CharField(default='742',max_length=100)
debt_to_income = models.CharField(default='0.33',max_length=100)
income_verified = models.CharField(default='',max_length=100)
default_risk_scorecard = models.CharField(default='',max_length=100)
delinquent_risk_scorecard_101 = models.CharField(default='',max_length=100)
delinquent_risk_scorecard_102 = models.CharField(default='',max_length=100)
PreferredPhone = models.CharField(default='',max_length=500)
DateOfBirth = models.CharField(default='',max_length=500)
Email = models.CharField(default='',max_length=500)
FirstName = models.CharField(default='',max_length=500)
LastName = models.CharField(default='',max_length=500)
LoanPurpose = models.CharField(default='',max_length=500)
LoanAmount  = models.CharField(default='',max_length=500)
OwnOrRent = models.CharField(default='',max_length=500)
RentAmount = models.CharField(default='',max_length=500)
temporaryPassword = models.CharField(default='',max_length=100)
MortgagePayment = models.CharField(default='',max_length=500)
Address1 = models.CharField(default='',max_length=500)
City = models.CharField(default='',max_length=500)
State = models.CharField(default='',max_length=500)
Zip = models.CharField(default='',max_length=500)
CurrentAddressTwoYears = models.CharField(default='',max_length=500)
PreviousAddress1 = models.CharField(default='',max_length=500)
PreviousCity = models.CharField(default='',max_length=500)
PreviousState = models.CharField(default='',max_length=500)
PreviousZip = models.CharField(default='',max_length=500)
ActiveDutyOrVeteran = models.CharField(default='',max_length=500)
TerminalServiceDate = models.CharField(default='',max_length=500)
MilitaryRank = models.CharField(default='',max_length=500)
MilitaryAllotment = models.BooleanField(default=False)
DirectDeposit = models.BooleanField(default=False)
checkingapplicationcomments = models.CharField(default='',max_length=5000)
incomeverificationcomments = models.CharField(default='',max_length=5000)
voidedcheckcomments = models.CharField(default='',max_length=5000)
identificationcomments = models.CharField(default='',max_length=5000)
creditcardstatementscomments = models.CharField(default='',max_length=5000)
checkingapplicationSubmitted = models.BooleanField(default=False)
incomeverificationSubmitted = models.BooleanField(default=False)
voidedcheckSubmitted = models.BooleanField(default=False)
identificationSubmitted = models.BooleanField(default=False)
creditcardstatementsSubmitted = models.BooleanField(default=False)
checkingapplicationAccepted = models.BooleanField(default=False)
incomeverificationAccepted = models.BooleanField(default=False)
voidedcheckAccepted = models.BooleanField(default=False)
identificationAccepted = models.BooleanField(default=False)
creditcardstatementsAccepted = models.BooleanField(default=False)
MilitaryServiceYears = models.CharField(default='', max_length=5000)
EmployerName = models.CharField(default='',max_length=500)
JobTitle = models.CharField(default='',max_length=500)
IncomeOther = models.CharField(default='0',max_length=500)
IncomeOther2 = models.CharField(default='0',max_length=500)
CoApp_IncomeOther = models.CharField(default='0',max_length=500)
IncomeOther3 = models.CharField(default='0',max_length=500)
IncomeTotal = models.CharField(default='',max_length=500)
IncomeSource = models.CharField(default='',max_length=500)
SSN = models.CharField(default='',max_length=500)
PaymentsObligated = models.CharField(default='',max_length=500)
PaymentsObligatedAmount = models.CharField(default='',max_length=500)
CoApplicant = models.CharField(default='',max_length=500)
CoApp_DateOfBirth = models.CharField(default='',max_length=500)
CoApp_FirstName = models.CharField(default='',max_length=500)
CoApp_LastName = models.CharField(default='',max_length=500)
CoApp_OwnOrRent = models.CharField(default='',max_length=500)
CoApp_RentAmount = models.CharField(default='',max_length=500)
CoApp_MortgagePayment = models.CharField(default='',max_length=500)
CoApp_StreetAddress = models.CharField(default='',max_length=500)
CoApp_City = models.CharField(default='',max_length=500)
CoApp_State = models.CharField(default='',max_length=500)
CoApp_Zip = models.CharField(default='',max_length=500)
CoApp_Phone = models.CharField(default='',max_length=500)
CoApp_Email = models.CharField(default='',max_length=500)
CoApp_SSN = models.CharField(default='',max_length=500)
CoApp_EmployerName = models.CharField(default='',max_length=500)
CoApp_IncomeGross = models.CharField(default='',max_length=500)
CoApp_IncomeSource = models.CharField(default='',max_length=500)
CoApp_IncomeTotal = models.CharField(default='',max_length=500)
ReferFriend = models.CharField(default='',max_length=500)
Consent_Value = models.CharField(default='',max_length=500)
CoApp_Consent_Value = models.CharField(default='',max_length=500)
CoApp_CP_Authorization = models.CharField(default='',max_length=500)
CoApp_TCPA_Release = models.CharField(default='',max_length=500)
CP_Authorization = models.CharField(default='',max_length=500)
TCPA_Release = models.CharField(default='',max_length=500)
CoApp_RelationToApplicant = models.CharField(default='',max_length=500)
GrossAnnualIncome = models.CharField(default='0',max_length=500)
decision = models.CharField(default='',max_length=500)
originationFee = models.CharField(default='',max_length=500)
apr = models.CharField(default='',max_length=500)
interestRate = models.CharField(default='',max_length=500)
interestRatePercent = models.CharField(default='',max_length=500)
monthlyPayment = models.CharField(default='',max_length=500)
term = models.CharField(default='36',max_length=500)
timeStamp = models.DateTimeField(default=datetime.now())
'''
import re
lst = s.split('\n')
model_list = []
for item in lst:
        res = re.findall('\S+',item)
        if len(res) > 0:
                model_list.append(res[0])

result = ''
for m in model_list:
        result += m
        result += '\t=\t\'\'' 
        result += '\n\n'

fout = open('model_list.py','w')
fout.write(result)
fout.close()



